### ISSUE TITLE
Discuss: Alternative tools

### ISSUE THREAD

**Issue by PerryFinn** [RicardoValdovinos/vite-react-boilerplate#1]
Do you consider using [Rome](https://rome.tools/) instead of prettier and eslint？

**Comment by RicardoValdovinos** [comment]
I've only just glanced at Rome but it seems like an interesting tool. However, there are a few reasons I went with ESLint and Prettier.

1. **Ubiquity** - Most developers will have heard of ESLint and Prettier. Everyone knows how to setup an ESLint or Prettier config and when it comes to providing a template that provides reasonable defaults, having ubiquitous tools is helps reduce the cognitive overhead that comes with making changes to or using the software.
2. **Unix Tools Philosophy** - "The tools philosophy was to have small programs to accomplish a particular task instead of trying to develop large monolithic programs to do a large number of tasks". In other words, having specific tools for the job without worrying about the coupling between them. Rome does seem like a good alternative but the main issue it presents is that it bundles tools with different purposes together. In the event that someone wants to use Prettier instead of the included Rome formatter, well, at worst, they have conflicting formatters that requires one of them to be removed and at best unused code is bundled that can't be removed without also removing the linter.
3. **Template Flexibility** - The template itself does not include much aside from the configs. Replacing ESLint and Prettier, or any other tool for that matter, is encouraged and should be done to help tailor the template to the given problem domain.
