### ISSUE TITLE
Can we introduce same boilerplate for JavaScript as well 

### ISSUE THREAD

**Issue by marxyes** [RicardoValdovinos/vite-react-boilerplate#12]

**Comment by RicardoValdovinos** [comment]
Hello,

This project is intended to be TypeScript focused. Type safety was one of the underlying principles behind the design of this project and most of the packages (where available) share the same philosophy. Additionally, another goal keep code boilerplate to a minimum so that developers were free to hit the ground running, so to speak.

If JavaScript boilerplate is something you require for your projects you can of course fork the project and have a template suited for your needs ready to go.
